# Generated by Django 3.0.8 on 2020-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articles_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
